
title: "Ivan Maslov: Full-Stack Web Engineer"
description: > 
  Ivan Maslov: Full-Stack Web Engineer Personal Site.
baseurl: "" 
blogurl: "/blog"
url: "http://studentivan.ru" 

disqus:
  shortname: studentivan

# Contacts

public_profiles:
  - title: github
    username: studentIvan
    url: https://github.com/
    color: "#a8a8a8"
  - title: habrahabr
    username: student_ivan
    url: https://habrahabr.ru/users/
    icon: header
    color: "#8baab5"
  - title: vk.com
    username: dr.tranquility
    url: https://vk.com/
    icon: vk
    color: "#45668e"
  - title: facebook
    username: ivan.tranquility
    url: https://www.facebook.com/
    color: "#3b5998"
  - title: linkedin
    username: drtranquility
    url: https://www.linkedin.com/in/
    color: "#007bb6"
    visible: false
  - title: twitter
    username: IvanTranquility
    url: https://twitter.com/
    color: "#00aced"
  - title: moikrug
    username: studentivan
    url: https://moikrug.ru/
    icon: certificate
    color: "#b3b3b3"
  - title: instagram
    username: studentivan
    url: http://instagram.com/
    visible: false
    color: "#517fa4"
  - title: duolingo
    username: IvanTranqu1
    url: https://www.duolingo.com/
    icon: comments-o
    color: "#71b200"
  - title: upwork
    username: ivanmaslov
    url: https://www.upwork.com/fl/
    icon: desktop
    color: "#5bbc2e"

skype_username:  radio.coder  # skype:radio.coder?call
facetime_number:  "79992284007"  # facetime:79995643839
phone_number:  "+79992284007"  # tel:+79995643839
phone_number_pretty:  "+7 (999) 228-4-007"
email: mail@studentivan.ru
email_hash: d58e6abd5a8c6a45366797e28d6bdf21

pgp_public_key: "E69E1D98.asc"

# Build settings
markdown: kramdown
theme: minima
timezone: Europe/Samara
# highlighter: pygments 

menu:
  - home
  - portfolio
  - resume
  - samples

defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"